### ISSUE TITLE
nix-related CI failure

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache-chai#43]
Integration tests fail in CI with

```
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```

Probably caused by https://github.com/cachix/install-nix-action/issues/148

For a full log, see [this job](https://github.com/informalsystems/apalache-chai/actions/runs/4363416401/jobs/7629484732)

**Comment by thpani** [comment]
@shonfeder do you remember why we set `install_url` here?

https://github.com/informalsystems/apalache-chai/blob/9e51e69b25d99cafa607a1bbbc5c2a776b178796/.github/workflows/main.yml#L130-L133

**Comment by shonfeder** [comment]
I don’t remember, but following the link on the comment on that step I found this comment from past me https://github.com/actions/cache/issues/324#issuecomment-944471178

it seems I took this from a workaround at a link which no longer exists :)

probably the nix setup here needs to be updated and reworked.
